version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  watcher:
    build: ./.
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env